/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;
import java.util.Arrays;

public  class Library {
    static int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };
    //problem 1
    public static int[] roll(int n){
        int rolls [] =new int[n];
        for(int i=0;i<rolls.length;i++){
            int randomRolls=(int)Math.ceil(Math.random() * 6);
            rolls[i]=randomRolls;
        }
        return rolls;

    }

    // end of problem 1 solution

    //start of second problem
    public static boolean containsDuplicates(int [] array){
        for(int i=0;i<array.length;i++) {
            for(int j=i+1;j<array.length;j++){
                if(array[i]==array[j]){
                    System.out.println("the duplicated value is => "+ array[j]);
                    return true;

                }

            }

        }
        return false;
    }
    //end of the second problem

    //start of the third problem
    public static double average(int [] arr){
        int sum=0;
        for (int i=0;i<arr.length;i++) {
            sum+=arr[i];
        }
        return sum/arr.length;
    }
//end of the third problem.

    //the start of the fourth problem.
    public static int[] arrayOfArray(int [] [] matrix){
        int rowSum=0;
        int total=0;
        int[]rowAvg=new int[matrix.length];
        for(int row=0;row<matrix.length;row++){
            rowSum=0;
            for (int column=0;column<matrix[row].length;column++){
                rowSum+=matrix[row][column];
                //total += matrix[row][column];
            }
            rowAvg[row]=rowSum/matrix[row].length;

        }
        return rowAvg;
    }
    public static void lowestAndHighestAvg(int[]temp){
        int min=temp[0];
        int max=temp[0];
        for(int i=1;i<temp.length;i++){
            if(temp[i]<min){
                min=temp[i];
            }
        }
        for(int i=1;i<temp.length;i++){
            if(temp[i]>max){
                max=temp[i];
            }
        }
        System.out.println("lowest temp avg => "+min);
        System.out.println("highest temp avg => "+max);
    }
    //the end of the fourth problem!


    public static void main(String[] args) {
        System.out.println(Arrays.toString(roll(5)));
        int[] myArray = new int[]{1,2,3,3,5,10};

        System.out.println(containsDuplicates(myArray));
        System.out.println(average(myArray));
        lowestAndHighestAvg((arrayOfArray(weeklyMonthTemperatures)));


    }
}
