/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant res=new Restaurant("Alakeel","JD");
        res.addReview(5,"this restaurant has a very great burger to eat","Farah Jamal");;
        //res.updateRate(4.75);
        res.addReview(3.5,"I hate this restaurant, a little ","Severus Snape");
        res.addReview(4.5,"I love food but this restaurant the best ","Ron weasly");
        res.addReview(2,"eat is useless reading more effective","Harmony");

        //System.out.println(res);

        System.out.println(res+"\n"+res.reviews);
        User user=new User();
        System.out.println(res.reviews);

        user.findReviews(res.reviews,"Omar");
        System.out.println(res.reviews);




    }
}
