/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import com.sun.org.apache.bcel.internal.classfile.LineNumber;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class Main {
    public static void ReadFile(String path){
        Scanner scnr = null;
        String response = "";
        int lineNumber = 1;

        try {
            scnr = new Scanner(new BufferedReader(new FileReader("./lib/src/main/resources/" + path)));
            String lines;
            while (scnr.hasNextLine()) {
                lines = scnr.nextLine();
                response += errorChecker(lines, lineNumber);
                lineNumber++;
            }
        } catch (FileNotFoundException e) {
            System.out.println("The file was not found");
        } finally {
            if (scnr != null) {
                scnr.close();
            }
        }
        if (response.equals("")) System.out.println("The file has no missing semicolons");
        else System.out.println(response);
    }

    private static String errorChecker(String line, int lineNumber) {
        char openCurly = '{';
        char closeCurly = '}';
        char semi = ';';
        char last = ' ';
        boolean ifCheck = line.contains("if");
        boolean elseCheck = line.contains("else");
        boolean singleQuoteCheck=line.contains("'");
        StringBuilder response = new StringBuilder();

        if (line.length() != 0) {
            last = line.charAt(line.length() - 1);
        }

        if (!ifCheck && !elseCheck && last != openCurly && last != closeCurly && line.length() != 0 && last != semi) {
            response.append("Line ").append(lineNumber).append(": Missing semicolon").append("\n");
        }
        if(!singleQuoteCheck){
            response.append(("Line")).append(lineNumber).append(": has double quotes").append("\n");
        }
        return response.toString();

    }
    public static void main(String[] args) throws FileNotFoundException {
        Scanner input = new Scanner(new File(args[0]));
        while(input.hasNext()){
            ReadFile(input.nextLine());

        }

        System.out.println();
    }
}
