/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void ResturantName() {
        Restaurant res=new Restaurant("Alakeel","JD");
        assertEquals("Resturant Name {Mcdonalds} Rate {5.0} Price Cat {2.0$ }\n" +
                "[]",res.toString());
    }
    @Test void ResturantReview() {
        Review rest=new Review(2,"It is a good resturant","Farah Jamal");
        assertEquals("Review {It is a good resturant} Author {Farah Jamal} Rate {2.0}",rest.toString());
    }
    @Test void addMutiplerev(){
        Restaurant res=new Restaurant("Mcdonalds","JD");

        res.addReview(3,"good one","farah");
        res.addReview(5,"good food","ahmad");
        res.addReview(3,"yumy","khair");
        assertEquals("Restaurant{name='Alakeel', stars=3.0, priceCat='JD'}\n" +
                " all reviews:  \n" +
                "[Review{rate=3.0, body='good one', author='farah'}, Review{rate=5.0, body='good food', author='ahmad'}, Review{rate=3.0, body='yumy', author='khair'}]\n",res.toString());

    }
}